spring.application.name=EjercicioUno
##Properties personales
frase.woe=Venid a Woe pls
##H2
spring.datasource.url=jdbc:h2:file:C:/Users/Xelphil/Desktop/JavaTaos/Ejercicio2/PracticasJava/src/main/resources/bbdd/bbdd
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2